# test
# rerun
name: Create release
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      skipped: ${{ steps.changelog.outputs.skipped }}
      clean_changelog: ${{ steps.changelog.outputs.clean_changelog }}
      tag: ${{ steps.changelog.outputs.tag }}
    steps:
      - uses: actions/checkout@v2        
        id: checkout
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          output-file: "false"
          skip-version-file:   "true"
          skip-commit: "true"
  release: 
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: publish
        uses: actions/create-release@v1
        if: ${{ needs.build.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ needs.build.outputs..tag }}
          release_name: ${{ needs.build.outputs..tag }}
          body: ${{ needs.build.outputs..clean_changelog }} 
